### ISSUE TITLE
Route suggestion bundle

### ISSUE THREAD

**Issue by austinhuang0131** [TransitTracker/extras#1]
Use the suggestion button every time sorta pointless so I'll just comment everything in this thread

**Comment by FelixINX** [comment]
I can also give you admin access if that's easier with you?

**Comment by austinhuang0131** [comment]
nah, it's cuz I currently have a midterm break, it's not like I'm available long-term lol

## Collège Sainte-Anne

[source](http://secondaire.sainteanne.ca/wp-content/uploads/2015/12/STM_secondaire_horaire_autobus_speciaux_2018-2019.pdf) (old)

### 411E

#### Morning

* Stops: 58485 (Gare Beaconsfield) => 57238 (School), non-stop
* Trips:
  * 6:58: `221218717`
  * 7:00: `221218110`, `221219565`
  * 7:07: `221217492`, `221220688`

#### Evening

* Stops: 61378 (School, fake stop) => 58591 (Terminus McDonald), regular 411 stops after Dorval
* Trips:
  * 14:51: `221220691`
  * ~15:05: `221220697`, `221220700`, `222767532`
  * 15:28: `221220694`

**Comment by austinhuang0131** [comment]
Anyways, some more general suggestions:

* sort stops by stop sequence please, not stop id
* add stop names to real stops (this will make figuring out trips much easier)
* use start/end stop to determine headsign so to beat twice-annual GTFS data changes that will casually invalidate all trip IDs

**Comment by FelixINX** [comment]
Well thanks for your help, I really appreciate it! I'll add you to the contributors list. I will also import [your list](https://github.com/austinhuang0131/stm-shuttle-tracker/wiki/Fake-STM-Stops) if that's ok with you?

> sort stops by stop sequence please, not stop id **Oh yes, I saw that error! The update has just not been pushed yet** :smiley:
> add stop names to real stops (this will make figuring out trips much easier) **I'll see what I can do**
> use start/end stop to determine headsign so to beat twice-annual GTFS data changes that will casually invalidate all trip IDs, at least that's what I use on my app so to make it completely independent of trip IDs **That's a good idea! However, I do have to keep the trip ID so Transit Tracker and others app can keep track of the trips without having to rewrite the functionnality. It's also harder with Industrial trips that makes the same route multiple times a day (e.g. 407I).**

My "dream" is to make an unified static GTFS with both normal data and extra trips within 24 hrs of any board change.

**Comment by austinhuang0131** [comment]
Sure, also don't forget I also offer a [trips.txt](https://github.com/austinhuang0131/stm-shuttle-tracker/blob/master/trips.txt)

Yeah I meant mass-assign headsigns to trip IDs by start/end stop

**Comment by FelixINX** [comment]
Thanks for that trips.txt file!

**Comment by FelixINX** [comment]
Changes are now live on the server, I'll fill out the existing trips and stops over the week.

**Comment by austinhuang0131** [comment]
meh, there's no "enjoy"ment now

pretty much skimmed through all your E stops and pushed a "second batch" on the wiki
